opus_defines.h: disable restrict with gcc < 3.4
With gcc-3.3, building opus fails with the following error:

In file included from silk/float/pitch_analysis_core_FLP.c:38:
celt/pitch.h:53: error: invalid use of `restrict'

This is because __restrict is broken with gcc < 3.4. See:
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=6392

Therefore, disable restrict with gcc versions older than 3.4.